from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from urllib.parse import quote

from .discovery import detect, files
from .paths import index_dir, okf_dir


MANIFEST = "manifest.json"


def _source_files(root: Path) -> list[Path]:
    bundle = okf_dir(root)
    if not bundle.is_dir():
        raise ValueError("Knowledge bundle is missing; run `okf-agent init` first.")
    paths = [path for path in bundle.rglob("*.md") if path.is_file() and not path.is_symlink()]
    manifest = bundle / "manifest.yaml"
    if manifest.is_file() and not manifest.is_symlink():
        paths.append(manifest)
    paths.extend(path for path in files(root) if path.is_file() and not path.is_symlink())
    unique = {path.relative_to(root).as_posix(): path for path in paths}
    return [unique[name] for name in sorted(unique)]


def _output_path(root: Path, output: Path | None) -> Path:
    target = (output or (index_dir(root) / "site")).resolve()
    if output is None:
        try:
            target.relative_to(index_dir(root).resolve())
        except ValueError as exc:
            raise ValueError("Default documentation output must stay inside `.okf-index/`.") from exc
    return target


def _digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _title(path: Path, content: str) -> str:
    for line in content.splitlines():
        match = re.match(r"^#\s+(.+?)\s*#*\s*$", line)
        if match:
            return match.group(1)
    return path.stem.replace("-", " ").replace("_", " ").title()


def _read_json(path: Path) -> dict | None:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else None
    except (OSError, json.JSONDecodeError):
        return None


def build_docs(root: Path, output: Path | None = None) -> dict[str, object]:
    """Copy the curated knowledge bundle into a deterministic local wiki tree."""
    root = root.resolve()
    target = _output_path(root, output)
    sources = _source_files(root)
    source_hashes: dict[str, str] = {}
    generated: dict[str, bytes] = {}
    pages: list[tuple[str, str]] = []

    for source in sources:
        relative = source.relative_to(root).as_posix()
        content = source.read_bytes()
        source_hashes[relative] = _digest(content)
        if source.suffix.lower() == ".md":
            page_path = f"source/{relative}"
            generated[page_path] = content
            pages.append((page_path, _title(source, content.decode("utf-8", errors="replace"))))

    facts = detect(root)
    repository_page = (
        f"# {root.name} Repository\n\n"
        "## Detected project facts\n"
        f"- Languages: {', '.join(facts['languages']) or 'unknown'}\n"
        f"- Framework hints: {', '.join(facts['framework_hints']) or 'none'}\n"
        f"- Manifests: {', '.join(facts['manifests']) or 'none'}\n\n"
        "These facts are extracted from repository files. Curated explanations live in the linked knowledge pages.\n"
    ).encode("utf-8")
    generated["repository.md"] = repository_page
    pages.insert(0, ("repository.md", f"{root.name} Repository"))

    index_lines = [f"# {root.name} Repository Wiki", "", "## Pages", ""]
    for page_path, title in pages:
        index_lines.append(f"- [{title}]({quote(page_path, safe='/')})")
    index_lines.append("")
    generated["index.md"] = "\n".join(index_lines).encode("utf-8")

    previous = _read_json(target / MANIFEST)
    output_hashes = {name: _digest(content) for name, content in sorted(generated.items())}
    manifest_data = {
        "schema_version": 1,
        "sources": source_hashes,
        "outputs": output_hashes,
    }
    generated[MANIFEST] = (json.dumps(manifest_data, indent=2, sort_keys=True) + "\n").encode("utf-8")

    # Remove only files previously recorded as generated by this tool.
    if previous and isinstance(previous.get("outputs"), dict):
        current_paths = set(output_hashes)
        for stale_name in previous["outputs"]:
            if not isinstance(stale_name, str):
                continue
            stale = (target / stale_name).resolve()
            try:
                stale.relative_to(target)
            except ValueError:
                continue
            if stale_name not in current_paths and stale.is_file():
                stale.unlink()

    for name, content in generated.items():
        destination = (target / name).resolve()
        try:
            destination.relative_to(target)
        except ValueError as exc:
            raise ValueError(f"Generated documentation path escapes output directory: {name}") from exc
        destination.parent.mkdir(parents=True, exist_ok=True)
        if not destination.exists() or destination.read_bytes() != content:
            destination.write_bytes(content)

    return {"output": str(target), "pages": len(pages), "sources": len(source_hashes)}


def check_docs(root: Path, output: Path | None = None) -> dict[str, object]:
    root = root.resolve()
    try:
        target = _output_path(root, output)
    except ValueError as exc:
        return {"ok": False, "errors": [str(exc)], "output": str(output or index_dir(root) / "site")}
    errors: list[str] = []
    manifest = _read_json(target / MANIFEST)
    if not manifest or manifest.get("schema_version") != 1:
        return {"ok": False, "errors": ["Documentation build is missing or has an invalid manifest; run `okf-agent docs build`"], "output": str(target)}

    try:
        current_sources = {path.relative_to(root).as_posix(): _digest(path.read_bytes()) for path in _source_files(root)}
    except (OSError, ValueError) as exc:
        return {"ok": False, "errors": [str(exc)], "output": str(target)}
    if manifest.get("sources") != current_sources:
        errors.append("Documentation is stale because knowledge sources changed; run `okf-agent docs build`")

    output_hashes = manifest.get("outputs")
    if not isinstance(output_hashes, dict):
        errors.append("Documentation manifest has no valid outputs map")
    else:
        for name, expected in output_hashes.items():
            if not isinstance(name, str) or not isinstance(expected, str):
                errors.append("Documentation manifest contains an invalid output entry")
                continue
            path = (target / name).resolve()
            try:
                path.relative_to(target)
            except ValueError:
                errors.append(f"Generated documentation path escapes output directory: {name}")
                continue
            try:
                unchanged = path.is_file() and _digest(path.read_bytes()) == expected
            except OSError:
                unchanged = False
            if not unchanged:
                errors.append(f"Generated page is missing or changed: {name}")
    return {"ok": not errors, "errors": errors, "output": str(target)}
