from __future__ import annotations

import sys
from pathlib import Path


PROTOCOL = """## OKF Repository Protocol

Before planning or editing, run `okf-agent index .` when the index is absent, then retrieve repository context. After source changes, run `okf-agent update . --changed-files <changed paths>`. Before completion, run `okf-agent validate .`. Preserve curated content outside OKF-generated blocks.
"""

CURSOR_RULE = """---
description: Maintain OKF repository knowledge before and after every coding task.
alwaysApply: true
---

""" + PROTOCOL

HOOKS = {
    "post-checkout": "okf-agent index . || exit 0\n",
    "post-merge": "okf-agent index . || exit 0\n",
    "pre-commit": "okf-agent update .\n",
    "pre-push": "okf-agent validate .\n",
}


def _command() -> str:
    executable = Path(sys.executable).parent / "Scripts" / "okf-agent.exe"
    return str(executable) if executable.exists() else "okf-agent"


def _append_protocol(path: Path) -> bool:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if "## OKF Repository Protocol" in current:
            return False
        path.write_text(current.rstrip() + "\n\n" + PROTOCOL, encoding="utf-8")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("# Repository Instructions\n\n" + PROTOCOL, encoding="utf-8")
    return True


def install(root: Path) -> list[Path]:
    installed: list[Path] = []
    for target in (root / "AGENTS.md", root / "CLAUDE.md", root / "GEMINI.md", root / ".claude" / "rules" / "okf.md"):
        if _append_protocol(target):
            installed.append(target)
    cursor_rule = root / ".cursor" / "rules" / "okf.mdc"
    if not cursor_rule.exists():
        cursor_rule.parent.mkdir(parents=True, exist_ok=True)
        cursor_rule.write_text(CURSOR_RULE, encoding="utf-8")
        installed.append(cursor_rule)
    hooks = root / ".git" / "hooks"
    if hooks.exists():
        for name, command in HOOKS.items():
            target = hooks / name
            if target.exists() and "# Generated by okf-agent" not in target.read_text(encoding="utf-8", errors="ignore"):
                continue
            try:
                target.write_text(
                    "#!/bin/sh\n# Generated by okf-agent\n" + command.replace("okf-agent", f"\"{_command()}\""),
                    encoding="utf-8",
                )
                target.chmod(0o755)
                installed.append(target)
            except OSError:
                continue
    return installed
