from __future__ import annotations

from pathlib import Path

AGENTS = """# OKF Agent Protocol

Before planning or editing, call `okf.get_change_context` (or `okf-agent index` then inspect `.okf/`). After code changes, call `okf.update_after_change` or `okf-agent update`. Before completion, call `okf.validate` or `okf-agent validate`. Preserve curated sections in `.okf/`; only generated blocks are machine-owned.
"""

HOOKS = {
    "post-checkout": "okf-agent index . || exit 0\n",
    "post-merge": "okf-agent index . || exit 0\n",
    "pre-commit": "okf-agent update . || exit 0\n",
    "pre-push": "okf-agent validate .\n",
}


def install(root: Path) -> list[Path]:
    (root / "AGENTS.md").write_text(AGENTS, encoding="utf-8")
    hooks = root / ".git" / "hooks"
    installed = [root / "AGENTS.md"]
    if hooks.exists():
        for name, command in HOOKS.items():
            target = hooks / name
            target.write_text("#!/bin/sh\n# Generated by okf-agent\n" + command, encoding="utf-8")
            try: target.chmod(0o755)
            except OSError: pass
            installed.append(target)
    return installed
